# fly.toml app configuration file generated for whichllm-backend on 2024-09-21T22:44:22+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whichllm-backend'
primary_region = 'lhr'

[build]

[[mounts]]
  source = 'data'
  destination = '/backend/data'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
