export const description = "WhichLLM operates using an algorithm which takes into account the average of most publically available benchmark scores to calculate a percentage score for each LLM. This percentage is used to rank the LLMs against each other. Each usecase has been allocated a number of benchmarks which best test for an LLM's ability at that usecase."

export const benchmarks = [
    { 'name': 'MMLU', 'subject': 'General' },
    { 'name': 'HellaSwag', 'subject': 'General', 'notes': 'Sentence completion' },
    { 'name': 'SuperGLUE', 'subject': 'General' },
    { 'name': 'WinoGrande', 'subject': 'General' },
    { 'name': 'ARC', 'subject': 'General' },
    { 'name': 'GPQA', 'subject': 'General' },
    { 'name': 'OpenBookQA', 'subject': 'General' },
    { 'name': 'BIG Bench Hard', 'subject': 'Advanced Reasoning' },
    { 'name': 'Chatbot Arena Elo', 'subject': 'Relative Performance', 'notes': 'User-based / Relative' },
    { 'name': 'MT-Bench', 'subject': 'Conversation' },
    { 'name': 'MATH', 'subject': 'Maths' },
    { 'name': 'GSM8K', 'subject': 'Maths' },
    { 'name': 'MGSM', 'subject': 'Maths' },
    { 'name': 'HumanEval', 'subject': 'Coding' },
    { 'name': 'MBPP', 'subject': 'Coding' },
    { 'name': 'USMLE', 'subject': 'Medicine' },
    { 'name': 'MedQA', 'subject': 'Medicine' },
    { 'name': 'LSAT', 'subject': 'Law' },
    { 'name': 'Bar Exam', 'subject': 'Law' },
    { 'name': 'Graduate Record Exam', 'subject': 'Law' },
    { 'name': 'DocVQA', 'subject': 'Image Understanding' },
    { 'name': 'MMMU', 'subject': 'Image Understanding' },
    { 'name': 'TextVQA', 'subject': 'Image Understanding' },
    { 'name': 'VATEX', 'subject': 'Video Understanding' },
    { 'name': 'CoVoST 2', 'subject': 'Speech Translation' },
    { 'name': 'FLEURS', 'subject': 'Speech Recognition' },
    { 'name': 'MAWPS', 'subject': 'Maths' },
    { 'name': 'PubMedQA', 'subject': 'Medicine' },
    { 'name': 'ChartQA', 'subject': 'Image Understanding', 'notes': 'Chart understanding' },
    { 'name': 'AI2D', 'subject': 'Image Understanding', 'notes': 'Science diagram understanding' },
    { 'name': 'MMLU Medicine', 'subject': 'Medicine', 'notes': 'Average score' },
    { 'name': 'MedMCQA', 'subject': 'Medicine' },
    { 'name': 'EQ Bench', 'subject': 'Emotional intelligence / creativity' }
]

